"DELETE FROM locations WHERE id=[location_id]"
"DELETE FROM roles WHERE id='[role_id]"
"DELETE FROM roles WHERE id=[role_id]"
"DELETE FROM routes WHERE id=[route_id]"
"DELETE FROM user_roles WHERE uid=[user_id] and role_id=[role_id]"
"INSERT INTO locations (name,address,uid) VALUES ([name],[address],[user_id])"
"INSERT INTO ride (uid, rid, lid, details, ride_date, name) VALUES ([user_id],[route_id],[location_id],[details],[ride_date],[name])"
"INSERT INTO roles (name) VALUES ([name])"
"INSERT INTO routes (name,link,uid) VALUES ([name], [link], [user_id])"
"INSERT INTO user_roles (uid, role_id) VALUES ([user_id],[role_id])"
"INSERT INTO users (first_name,last_name,hash,email) VALUES ([first_name],[last_name],[hash],[email])"
"SELECT first_name,last_name, email FROM users WHERE id=[user_id]"
"SELECT hash FROM users where email=[email]"
"SELECT id, first_name FROM users WHERE email=[email]"
"SELECT id,first_name,last_name, email FROM users"
"SELECT  id, first_name, last_name  FROM users"
"SELECT id FROM locations where name='$name'"
"SELECT id FROM roles where name=[role_name]"
"SELECT id FROM routes where name=[route_name]"
"SELECT id FROM users WHERE email=[email]"
"SELECT id, name FROM locations"
"SELECT  id,  name  FROM roles"
"SELECT id, name FROM routes"
"SELECT  locations.id as id, name, address, first_name, last_name FROM locations INNER JOIN  users ON locations.uid = users.id"
"SELECT  locations.id as id, name, address, first_name, last_name FROM locations INNER JOIN  users ON locations.uid = users.id WHERE users.id = [user_id]"
"SELECT name,address FROM locations WHERE uid=[user_id]"
"SELECT name as title, id, ride_date, details FROM ride WHERE uid=[user_uid]"
"SELECT ride.id as ride_id, users.id as user_id, first_name, last_name, ride.name AS title, ride_date, details, link, address, locations.name AS loc_name, ride.details as description FROM ride INNER JOIN users ON users.id = ride.uid INNER JOIN routes ON routes.id = ride.rid INNER JOIN locations ON locations.id = ride.lid"
"SELECT rid, uid, lid, name, details, ride_date FROM ride WHERE id=[user_id]"
"SELECT roles.name as name  FROM roles INNER JOIN user_roles ON  roles.id=user_roles.role_id INNER JOIN users on users.id = user_roles.uid WHERE users.id=[user_id"
"SELECT  routes.id as id, name, link, first_name, last_name FROM routes INNER JOIN  users ON routes.uid = users.id"
"SELECT routes.id as id, name, link, first_name, last_name FROM routes INNER JOIN  users ON routes.uid = users.id WHERE users.id = [user_id]"
"SELECT users.id AS uid, role_id, first_name, last_name, name FROM users INNER JOIN user_roles ON users.id = user_roles.uid INNER JOIN roles ON roles.id = user_roles.role_id"
"UPDATE locations SET name='$name', address='$addr' WHERE id=[id]"
"UPDATE ride SET uid=[user_id], rid=[route_id], lid=[location_id], details=[details], ride_date=[date], name=[name]"
"UPDATE routes SET name=[name], link=[link] WHERE id=[route_id]"
